dropout: 0.07470233738856523
embed_dim: 192
encoder_depth: 4
mlp_ratio: 4
num_heads: 8
num_sample: 8
num_steps: 100
objective: noise
pos_dim: 64
schedule: quad
wavenet:
  dropout: 0.2
  embed_dim: 32
  end_dim: 64
  mask_ratio: 0.75
