config_PEMS03:
  pos_dim: 96
  embed_dim: 96
  num_heads: 8
  encoder_depth: 2
  mlp_ratio: 1
  dropout: 0.2
  num_steps: 50
  schedule: quad
  num_sample: 8
  objective: input
  wavenet:
    embed_dim: 32
    end_dim: 64
    mask_ratio: 0.75
    dropout: 0.2
    blocks: 2
    layers: 3
config_PEMSBAY:
  pos_dim: 96
  embed_dim: 96
  num_heads: 8
  encoder_depth: 2
  mlp_ratio: 1
  dropout: 0.2
  num_steps: 50
  schedule: quad
  num_sample: 8
  objective: input
  wavenet:
    embed_dim: 32
    end_dim: 64
    mask_ratio: 0.75
    dropout: 0.2
config_BJAir:
  pos_dim: 96
  embed_dim: 96
  num_heads: 8
  encoder_depth: 2
  mlp_ratio: 1
  dropout: 0.2
  num_steps: 50
  schedule: quad
  num_sample: 8
  objective: noise
  wavenet:
    embed_dim: 32
    end_dim: 64
    mask_ratio: 0.75
    dropout: 0.2
config_GZAir:
  pos_dim: 96
  embed_dim: 96
  num_heads: 8
  encoder_depth: 2
  mlp_ratio: 1
  dropout: 0.2
  num_steps: 50
  schedule: quad
  num_sample: 8
  objective: noise
  wavenet:
    embed_dim: 32
    end_dim: 64
    mask_ratio: 0.75
    dropout: 0.2
config_SAWS:
  pos_dim: 96
  embed_dim: 96
  num_heads: 8
  encoder_depth: 2
  mlp_ratio: 1
  dropout: 0.2
  num_steps: 50
  schedule: quad
  num_sample: 8
  objective: noise
  wavenet:
    embed_dim: 32
    end_dim: 64
    mask_ratio: 0.75
    dropout: 0.2
config_SAWS_trial0:
  pos_dim: 64
  embed_dim: 192
  num_heads: 8
  encoder_depth: 4
  mlp_ratio: 4
  dropout: 0.07470233738856523
  num_steps: 100
  schedule: quad
  num_sample: 8
  objective: noise
  wavenet:
    embed_dim: 32
    end_dim: 64
    mask_ratio: 0.75
    dropout: 0.2
