_wandb:
    value:
        cli_version: 0.26.1
        e:
            efbiyillb56st5fji0kim9x5azzdkzfk:
                args:
                    - --model
                    - gwavenet
                    - --dataset_mode
                    - SAWS
                    - --pred_attr
                    - NA
                    - --enable_val
                    - --gpu_ids
                    - "0"
                    - --config
                    - config1
                    - --pretrain
                    - NA
                    - --save_best
                    - --t_len
                    - "48"
                    - --seed
                    - "2031"
                    - --eval_epoch_freq
                    - "10"
                    - --num_train_target
                    - "3"
                    - --num_threads
                    - "4"
                    - --batch_size
                    - "128"
                codePath: USTD/train.py
                codePathLocal: train.py
                cpu_count: 56
                cpu_count_logical: 56
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "943439200256"
                        used: "41026498560"
                email: chkkar002@myuct.ac.za
                executable: /home/chkkar002/envs/diffstg/bin/python
                git:
                    commit: e35b3a371125b0e5ae0970a44fe838dcf50a3d48
                    remote: git@github.com:GenevieveAkosua/Diffusion_Based_STGNNs.git
                gpu: NVIDIA A100-PCIE-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-e820ab77-d893-d4c3-5b32-6106e0ca3661
                host: srvrocgpu010.uct.ac.za
                memory:
                    total: "539923484672"
                os: Linux-5.14.0-687.29.1.el9_8.x86_64-x86_64-with-glibc2.34
                program: /scratch/chkkar002/Diffusion_Based_STGNNs/USTD/train.py
                python: CPython 3.9.25
                root: /scratch/chkkar002/Diffusion_Based_STGNNs/USTD
                slurm:
                    cluster_name: srvrochpc001
                    conf: /opt/slurm-23.11.5/etc/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x000100000000
                    cpu_bind_list: "0x000100000000"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "4"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: a100free
                    job_cpus_per_node: "4"
                    job_end_time: "1787075567"
                    job_gid: "1221947160"
                    job_gpus: "0"
                    job_group: eresearch_hpc_users
                    job_id: "1245408"
                    job_name: Test_ustd_covar_noheight_noyear
                    job_nodelist: srvrocgpu010
                    job_num_nodes: "1"
                    job_partition: a100
                    job_qos: a100free
                    job_start_time: "1787068367"
                    job_uid: "292132302"
                    job_user: chkkar002
                    jobid: "1245408"
                    launch_node_ipaddr: 137.158.158.180
                    localid: "0"
                    mem_per_node: "65536"
                    mpi_type: pmix
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: srvrocgpu010
                    nprocs: "4"
                    ntasks: "4"
                    pmix_mapping_serv: (vector,(0,1,1))
                    pmixp_abort_agent_port: "44795"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "33511"
                    pty_win_col: "213"
                    pty_win_row: "66"
                    script_context: prolog_task
                    srun_comm_host: 137.158.158.180
                    srun_comm_port: "38687"
                    step_id: "0"
                    step_launcher_port: "38687"
                    step_nodelist: srvrochpc102
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /scratch/chkkar002/Diffusion_Based_STGNNs/USTD
                    submit_host: srvrochpc102.uct.ac.za
                    task_pid: "3027229"
                    tasks_per_node: "4"
                    topology_addr: switch-0.switch-1.srvrocgpu010
                    topology_addr_pattern: switch.switch.node
                startedAt: "2026-08-18T16:00:56.455513Z"
                writerId: efbiyillb56st5fji0kim9x5azzdkzfk
        m: []
        python_version: 3.9.25
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.9.25
            "5": 0.26.1
            "10":
                - 20
            "12": 0.26.1
            "13": linux-x86_64
batch_size:
    value: 128
beta:
    value: 1
checkpoints_dir:
    value: ./checkpoints/SAWS
config:
    value: config1
continue_train:
    value: false
covariate_dim:
    value: 1
dataset_mode:
    value: SAWS
delete_col:
    value:
        - u_speed
        - v_speed
        - latitude
        - longitude
dropout:
    value: 0.2
embed_dim:
    value: 32
enable_curriculum:
    value: false
enable_neptune:
    value: false
enable_val:
    value: true
enable_visual:
    value: false
end_dim:
    value: 64
epoch:
    value: latest
epoch_count:
    value: 0
eval_epoch_freq:
    value: 10
file_time:
    value: 20260818T180055
gpu_ids:
    value:
        - 0
init_gain:
    value: 0.02
init_type:
    value: xavier
isTrain:
    value: true
load_iter:
    value: 0
lr:
    value: 0.001
lr_decay_iters:
    value: 50
lr_policy:
    value: cosine
mask_ratio:
    value: 0.75
max_dataset_size:
    value: .inf
mean:
    value: 17.288782119750977
model:
    value: gwavenet
n_epochs:
    value: 300
n_epochs_decay:
    value: 0
n_epochs_target:
    value: 100
n_epochs_target_increase:
    value: 150
name:
    value: gwavenet_NA_20260818T180055
neptune_project:
    value: ""
neptune_token:
    value: ""
num_nodes:
    value: 32
num_threads:
    value: 4
num_train_target:
    value: 3
num_train_target_end:
    value: 6
phase:
    value: train
pred_attr:
    value: NA
pretrain:
    value: NA
print_freq:
    value: 20
save_best:
    value: true
save_epoch_freq:
    value: 100
scale:
    value: 6.896627902984619
seed:
    value: 2031
serial_batches:
    value: false
spatial_dim:
    value: 64
t_len:
    value: 48
total_iters:
    value: 0
use_adj:
    value: true
verbose:
    value: false
y_dim:
    value: 1
